HTTP_OK=200
HTTP_OK_STR="ok"

HTTP_BAD_REQUEST=400
HTTP_BAD_REQUEST_STR="Bad Request"

HTTP_UNAUTHORIZED=401
HTTP_UNAUTHORIZED_STR="Unauthorized"

HTTP_FORBIDEN=403
HTTP_FORBIDEN_STR="Forbiden"

HTTP_REQUEST_TIMEOUT=408
HTTP_REQUEST_TIMEOUT_STR="Request Timeout"

HTTP_INTERL_ERROR=500
HTTP_INTERL_ERROR_STR="Internal Error"
