LOG_DIR="/var/log/analyze"
RUN_DIR="/var/run/analyze"
LIB_DIR="/var/lib/analyze"
SHARE_DIR="/usr/share/analyze"
CONF_DIR="/etc/analyze"
ANALYZE_CONF_FILE="analyze.conf"

SEARCH_ENGINE="search_engine"
SEARCH_ENGINE_LIB_DIR='/'.join([LIB_DIR,SEARCH_ENGINE])
SEARCH_ENGINE_LOG_DIR='/'.join([LOG_DIR,SEARCH_ENGINE])
SEARCH_ENGINE_RUN_DIR='/'.join([RUN_DIR,SEARCH_ENGINE])
SEARCH_ENGINE_CONF_DIR='/'.join([CONF_DIR,SEARCH_ENGINE])
SEARCH_ENGINE_LOCK='/'.join([SEARCH_ENGINE_RUN_DIR,"lock"])
SEARCH_ENGINE_USER_INFO='/'.join([SEARCH_ENGINE_RUN_DIR,"user_info"])
SEARCH_ENGINE_UUID_FILE='/'.join([SEARCH_ENGINE_LIB_DIR,"uuid"])

REPORT_CONF_FILE='report_gen.conf'
REPORT="report"
REPORT_RUN_DIR='/'.join([RUN_DIR,REPORT])
